# Generated by Django 3.2.4 on 2021-06-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_name', models.CharField(db_index=True, max_length=255)),
                ('datum', models.JSONField(null=True)),
            ],
        ),
    ]
