# Generated by Django 3.2.3 on 2021-05-26 14:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('datum_name', models.CharField(max_length=255)),
                ('datum', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
