# Generated by Django 3.2.3 on 2021-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_data_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datum_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
