import fp from 'lodash/fp';

export default class ObjectParser {
  constructor(object) {
    this.object = object;
  }

  // Getter
  get area() {
    return this.calcArea();
  }

  parseObject() {
    const data = fp.map(
      fp.pick([
        'symbol',
        'price',
        'price_btc',
        'market_cap',
        'percent_change_24',
        'percent_change_7d',
        'percent change_30d',
        'volume_24h',
        'max_supply',
        'timeSeries',
        'social_dominance',
        'social_contributors_calc_24h_previous',
        'url_shares_calc_24h_previous',
        'tweet_spam_calc_24h_previous',
        'news_calc_24h_previous',
        'average_sentiment_calc_24h_previous',
        'social_score_calc_24h_previous',
        'social_volume_calc_24h_previous',
        'alt_rank_30d_calc_24h_previous',
        'alt_rank_calc_24h_previous',
        'social_dominance_calc_24h',
        'social_dominance_calc_24h_percent',
        'social_contributors_calc_24h',
        'social_contributors_calc_24h_percent',
        'url_shares_calc_24h',
        'url_shares_calc_24h_percent',
        'tweet_spam_calc_24h',
        'tweet_spam_calc_24h_percent',
        'news_calc_24h',
        'news_calc_24h_percent',
        'average_sentiment_calc_24h',
        'average_sentiment_calc_24h_percent',
        'social_score_calc_24h',
        'social_score_calc_24h_percent',
        'social_volume_calc_24h',
        'social_volume_calc_24h_percent',
        'asset_id',
        'time',
        'open',
        'low',
        'volume',
        'market_cap',
        'url_shares',
        'unique_url_shares',
        'reddit_posts',
        'reddit_posts_score',
        'reddit_comments',
        'reddit_comments_score',
        'tweets',
        'tweet_spam',
        'tweet_followers',
        'tweet_quotes',
        'tweet_retweets',
        'tweet_replies',
        'tweet_favorites',
        'tweet_sentiment1',
        'tweet_sentiment2',
        'tweet_sentiment3',
        'tweet_sentiment4',
        'tweet_sentiment5',
        'tweet_sentiment_impact1',
        'tweet_sentiment_impact2',
        'tweet_sentiment_impact3',
        'tweet_sentiment_impact4',
        'tweet_sentiment_impact5',
        'social_score',
        'average_sentiment',
        'sentiment_absolute',
        'sentiment_relative',
        'price_score',
        'social_impact_score',
        'correlation_rank',
        'galaxy_score',
        'volatility',
        'alt_rank',
        'alt_rank_30d',
        'market_cap_rank',
        'percent_change_24h_rank',
        'volume_24h_rank',
        'social_volume_24h_rank',
        'social_score_24h_rank',
        'social_contributors',
        'social_volume',
        'social_volume_global',
        'social_dominance',
        'market_cap_global',
        'market_dominance',
        'news',
        'tags',
        'close',
      ]),
      this.object
    );
    return data;
  }
}
